name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  common_models:
    path: ../common_models/
  csv: ^5.0.2
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  dartz: ^0.10.1
  dotenv: ^4.1.0
  equatable: ^2.0.5
  fluent_validation: ^2.1.1
  freezed_annotation: ^2.2.0
  gsheets: ^0.4.2
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
